/*
 * Minimal btstack configuration to support BLE peripheral use on Pico 2 Wireless
 */

#ifndef BTSTACK_CONFIG_H
#define BTSTACK_CONFIG_H

#ifndef ENABLE_BLE
#define ENABLE_BLE
#endif
#ifndef ENABLE_LE_PERIPHERAL
#define ENABLE_LE_PERIPHERAL
#endif
#ifndef ENABLE_LE_SIGNED_WRITE
#define ENABLE_LE_SIGNED_WRITE
#endif

#ifndef ENABLE_LOG_INFO
#define ENABLE_LOG_INFO
#endif
#ifndef ENABLE_LOG_DEBUG
#define ENABLE_LOG_DEBUG
#endif

#ifndef MAX_ATT_DB_SIZE
#define MAX_ATT_DB_SIZE 1024
#endif

#ifndef HCI_ACL_PAYLOAD_SIZE
#define HCI_ACL_PAYLOAD_SIZE 1024
#endif
#ifndef HCI_INCOMING_PRE_BUFFER_SIZE
#define HCI_INCOMING_PRE_BUFFER_SIZE 6
#endif
#ifndef HCI_ACL_CHUNK_SIZE_ALIGNMENT
#define HCI_ACL_CHUNK_SIZE_ALIGNMENT 4
#endif
#ifndef HCI_ACL_OUTGOING_PRE_BUFFER_SIZE
#define HCI_ACL_OUTGOING_PRE_BUFFER_SIZE 4
#endif
#ifndef HCI_OUTGOING_PRE_BUFFER_SIZE
#define HCI_OUTGOING_PRE_BUFFER_SIZE 4
#endif

#ifndef NVM_NUM_DEVICE_DB_ENTRIES
#define NVM_NUM_DEVICE_DB_ENTRIES 4
#endif

#endif
#ifndef ENABLE_PRINTF_HEXDUMP
#define ENABLE_PRINTF_HEXDUMP
#endif
